name: prose_2to1

# shared attributes
dim_emb: 1024
dim_ffn: 2048
dropout: 0
n_head: 8
norm_first: true

patch_num: 8 # for input, number of patches per dimension
patch_num_output: 16 # for output, number of patches per dimension

carry_last_frame: 0

time_embed: learnable # select from continuous and learnable

embedder:
    # choose from [linear, conv, overlap_linear, fno, fourier] 
    type: conv
    dim: ${..dim_emb}
    patch_num: ${..patch_num}
    patch_num_output: ${..patch_num_output}

    time_embed: ${..time_embed}

    initialize_small_output: 0
    
    conv_dim: 32
    early_conv: 0

    deep: 0


data_encoder:
    n_layer: 2
    positional_embedding: null
    dim_emb: ${..dim_emb}
    dim_ffn: ${..dim_ffn}
    n_head: ${..n_head}
    dropout: ${..dropout}
    norm_first: ${..norm_first}

    custom_encoder: ${..custom_encoder}
    custom_attn: ${..custom_attn}
    rotary: ${..rotary}
    norm: ${..norm}
    
symbol_encoder:
    n_layer: 1
    positional_embedding: sinusoidal
    dim_emb: ${..dim_emb}
    dim_ffn: ${..dim_ffn}
    n_head: ${..n_head}
    dropout: ${..dropout}
    norm_first: ${..norm_first}

    custom_encoder: ${..custom_encoder}
    custom_attn: ${..custom_attn}
    rotary: ${..rotary}
    norm: ${..norm}
    
fusion:
    n_layer: 8
    type_embeddings: true
    dim_emb: ${..dim_emb}
    dim_ffn: ${..dim_ffn}
    n_head: ${..n_head}
    dropout: ${..dropout}
    norm_first: ${..norm_first}

    custom_encoder: ${..custom_encoder}
    custom_attn: ${..custom_attn}
    rotary: ${..rotary}
    norm: ${..norm}
    
data_decoder:
    n_layer: 8
    query_dim: 1 # time: 1, space: 2
    self_attn: 0 # 0: disable, 1: restricted self_attn, 2: full self_attn
    dim_emb: ${..dim_emb}
    dim_ffn: ${..dim_ffn}
    n_head: ${..n_head}
    dropout: ${..dropout}
    norm_first: ${..norm_first}
    patch_num_output: ${..patch_num_output}
    time_embed: ${..time_embed}

    final_ln: 1 # whether to have final norm layer

    custom_attn: ${..custom_attn}
    rotary: ${..rotary}
    norm: ${..norm}


custom_encoder: 1
custom_attn: 1
rotary: 0
norm: rms # select from [layer, group, rms]
    